FROM ubuntu:18.04

## basic ##
RUN apt update

RUN apt install gcc git curl vim apt-transport-https \
    ca-certificates gnupg-agent software-properties-common -y

RUN apt install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev -y

## docker ##
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
RUN apt-get update
RUN apt-get install docker-ce docker-ce-cli containerd.io -y

## docker compose ##
RUN curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose \
    && ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

## pyenv ##
RUN curl https://pyenv.run | bash
RUN echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ${HOME}/.profile
RUN echo 'eval "$(pyenv init -)"' >> ${HOME}/.profile
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> ${HOME}/.profile

## python 3.6.10 ##
RUN $HOME/.pyenv/bin/pyenv install 3.6.10
RUN $HOME/.pyenv/bin/pyenv global 3.6.10

## install api lib
RUN $HOME/.pyenv/versions/3.6.10/bin/pip3 install requests
RUN $HOME/.pyenv/versions/3.6.10/bin/pip3 install python-lib-flow.ci

## ssh config
RUN mkdir -p $HOME/.ssh
RUN echo "StrictHostKeyChecking=no" >> $HOME/.ssh/config